name: Build My JeOS Image
on:
  workflow_dispatch: # Botón manual de encendido

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Usamos Buildah para compilar tu Containerfile puro
      - name: Build Image using Buildah
        id: build-image
        uses: redhat-actions/buildah-build@v3
        with:
          image: mi-jeos-consola
          tags: latest
          containerfiles: |
            ./Containerfile
          oci: true

      # Exportamos el sistema operativo limpio directamente a un archivo para ti
      - name: Export Image File
        run: |
          podman save -o mi-jeos-consola.tar mi-jeos-consola:latest
          gzip mi-jeos-consola.tar

      # Subimos tu archivo .tar.gz para que lo descargues con un clic
      - name: Upload JeOS System Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mi-jeos-consola-sistema
          path: mi-jeos-consola.tar.gz
